apiVersion: apps/v1
kind: Deployment
metadata:
  name: instrumented-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instrumented-app
  template:
    metadata:
      labels:
        app: instrumented-app
    spec:
      containers:
        - name: app
          image: ghcr.io/open-telemetry/demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-metrics-collector.tracing.svc.cluster.local:4317
            - name: OTEL_SERVICE_NAME
              value: "instrumented-app"
---
apiVersion: v1
kind: Service
metadata:
  name: instrumented-app
spec:
  selector:
    app: instrumented-app
  ports:
    - port: 80
      targetPort: 8080
